### ISSUE TITLE
node:internal/modules/cjs/loader:1243   return process.dlopen(module, path.toNamespacedPath(filename));                  ^  Error: libuuid.so.1: cannot open shared object file: No such file or directory     at Module._extensions..node (node:internal/modules/cjs/loader:1243:18)     at Module.load (node:internal/modules/cjs/loader:1037:32)     at Module._load (node:internal/modules/cjs/loader:878:12)     at Module.require (node:internal/modules/cjs/loader:1061:19)     at require (node:internal/modules/cjs/helpers:103:18)     at Object.<anonymous> (/home/runner/AwainChess/node_modules/canvas/lib/bindings.js:3:18)     at Module._compile (node:internal/modules/cjs/loader:1159:14)     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)     at Module.load (node:internal/modules/cjs/loader:1037:32)     at Module._load (node:internal/modules/cjs/loader:878:12) {   code: 'ERR_DLOPEN_FAILED' }

### ISSUE THREAD

**Issue by king2022new** [joeymalvinni/ChessBot#6]
node:internal/modules/cjs/loader:1243
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libuuid.so.1: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1243:18)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/runner/AwainChess/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12) {
  code: 'ERR_DLOPEN_FAILED'
}

**Comment by joeymalvinni** [comment]
[If you are trying to host this on replit, check out this solution.](https://github.com/Automattic/node-canvas/issues/1893#issuecomment-1096988007) If not, please update your comment with more information.
